Telerik.Web.UI.RadMenuItemEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemEventArgs.initializeBase(this);
this._item=a;
this._domEvent=b||null;
};
Telerik.Web.UI.RadMenuItemEventArgs.prototype={get_item:function(){return this._item;
},get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.RadMenuItemEventArgs.registerClass("Telerik.Web.UI.RadMenuItemEventArgs",Sys.EventArgs);
Telerik.Web.UI.RadMenuItemCancelEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemCancelEventArgs.initializeBase(this);
this._item=a;
this._domEvent=b||null;
};
Telerik.Web.UI.RadMenuItemCancelEventArgs.prototype={get_item:function(){return this._item;
},get_domEvent:function(){return this._domEvent;
}};
Telerik.Web.UI.RadMenuItemCancelEventArgs.registerClass("Telerik.Web.UI.RadMenuItemCancelEventArgs",Sys.CancelEventArgs);
Telerik.Web.UI.RadMenuMouseOverEventArgs=function(a,b){Telerik.Web.UI.RadMenuMouseOverEventArgs.initializeBase(this,[a,b||null]);
};
Telerik.Web.UI.RadMenuMouseOverEventArgs.registerClass("Telerik.Web.UI.RadMenuMouseOverEventArgs",Telerik.Web.UI.RadMenuItemEventArgs);
Telerik.Web.UI.RadMenuMouseOutEventArgs=function(a,b){Telerik.Web.UI.RadMenuMouseOutEventArgs.initializeBase(this,[a,b||null]);
};
Telerik.Web.UI.RadMenuMouseOutEventArgs.registerClass("Telerik.Web.UI.RadMenuMouseOutEventArgs",Telerik.Web.UI.RadMenuItemEventArgs);
Telerik.Web.UI.RadMenuItemFocusEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemFocusEventArgs.initializeBase(this,[a,b||null]);
};
Telerik.Web.UI.RadMenuItemFocusEventArgs.registerClass("Telerik.Web.UI.RadMenuItemFocusEventArgs",Telerik.Web.UI.RadMenuItemEventArgs);
Telerik.Web.UI.RadMenuItemBlurEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemBlurEventArgs.initializeBase(this,[a,b||null]);
};
Telerik.Web.UI.RadMenuItemBlurEventArgs.registerClass("Telerik.Web.UI.RadMenuItemBlurEventArgs",Telerik.Web.UI.RadMenuItemEventArgs);
Telerik.Web.UI.RadMenuItemClickingEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemClickingEventArgs.initializeBase(this,[a,b||null]);
};
Telerik.Web.UI.RadMenuItemClickingEventArgs.registerClass("Telerik.Web.UI.RadMenuItemClickingEventArgs",Telerik.Web.UI.RadMenuItemCancelEventArgs);
Telerik.Web.UI.RadMenuItemClickedEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemClickedEventArgs.initializeBase(this,[a,b||null]);
};
Telerik.Web.UI.RadMenuItemClickedEventArgs.registerClass("Telerik.Web.UI.RadMenuItemClickedEventArgs",Telerik.Web.UI.RadMenuItemEventArgs);
Telerik.Web.UI.RadMenuItemOpeningEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemOpeningEventArgs.initializeBase(this,[a,b||null]);
};
Telerik.Web.UI.RadMenuItemOpeningEventArgs.registerClass("Telerik.Web.UI.RadMenuItemOpeningEventArgs",Telerik.Web.UI.RadMenuItemCancelEventArgs);
Telerik.Web.UI.RadMenuItemOpenedEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemOpenedEventArgs.initializeBase(this,[a,b||null]);
};
Telerik.Web.UI.RadMenuItemOpenedEventArgs.registerClass("Telerik.Web.UI.RadMenuItemOpenedEventArgs",Telerik.Web.UI.RadMenuItemEventArgs);
Telerik.Web.UI.RadMenuItemClosingEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemClosingEventArgs.initializeBase(this,[a,b||null]);
};
Telerik.Web.UI.RadMenuItemClosingEventArgs.registerClass("Telerik.Web.UI.RadMenuItemClosingEventArgs",Telerik.Web.UI.RadMenuItemCancelEventArgs);
Telerik.Web.UI.RadMenuItemClosedEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemClosedEventArgs.initializeBase(this,[a,b||null]);
};
Telerik.Web.UI.RadMenuItemClosedEventArgs.registerClass("Telerik.Web.UI.RadMenuItemClosedEventArgs",Telerik.Web.UI.RadMenuItemEventArgs);
Telerik.Web.UI.RadMenuItemPopulatingEventArgs=function(a,b){Telerik.Web.UI.RadMenuItemPopulatingEventArgs.initializeBase(this,[a]);
this._context=b;
};
Telerik.Web.UI.RadMenuItemPopulatingEventArgs.prototype={get_context:function(){return this._context;
}};
Telerik.Web.UI.RadMenuItemPopulatingEventArgs.registerClass("Telerik.Web.UI.RadMenuItemPopulatingEventArgs",Telerik.Web.UI.RadMenuItemCancelEventArgs);
Telerik.Web.UI.RadMenuItemPopulatedEventArgs=function(a){Telerik.Web.UI.RadMenuItemPopulatedEventArgs.initializeBase(this,[a]);
};
Telerik.Web.UI.RadMenuItemPopulatedEventArgs.registerClass("Telerik.Web.UI.RadMenuItemPopulatedEventArgs",Telerik.Web.UI.RadMenuItemEventArgs);
Telerik.Web.UI.RadMenuItemPopulationFailedEventArgs=function(b,a){Telerik.Web.UI.RadMenuItemPopulationFailedEventArgs.initializeBase(this,[b]);
this._errorMessage=a;
};
Telerik.Web.UI.RadMenuItemPopulationFailedEventArgs.prototype={get_errorMessage:function(){return this._errorMessage;
}};
Telerik.Web.UI.RadMenuItemPopulationFailedEventArgs.registerClass("Telerik.Web.UI.RadMenuItemPopulationFailedEventArgs",Telerik.Web.UI.RadMenuItemCancelEventArgs);
(function(){var e=$telerik.$,a=Telerik.Web.UI,c="rmItem",b="rmLink",d="rmTopArrow",g="rmBottomArrow",f="rmLeftArrow",h="rmRightArrow";
Type.registerNamespace("Telerik.Web.UI");
$telerik.findMenu=$find;
$telerik.toMenu=function(i){return i;
};
a.RadMenu=function(i){a.RadMenu.initializeBase(this,[i]);
this._childTypeName="Telerik.Web.UI.RadMenuItem";
this._selectedValue="";
this._itemData=null;
this._expandAnimation=new a.AnimationSettings({});
this._expandDelay=100;
this._collapseAnimation=new a.AnimationSettings({});
this._collapseDelay=500;
this._flow=a.ItemFlow.Horizontal;
this._defaultGroupSettings=new a.RadMenuItemGroupSettings({});
this._enableSelection=true;
this._enableAutoScroll=false;
this._autoScrollMinimumHeight=50;
this._autoScrollMinimumWidth=50;
this._enableRootItemScroll=false;
this._enableScreenBoundaryDetection=true;
this._enableRoundedCorners=false;
this._enableShadows=false;
this._clickToOpen=false;
this._childListElement=null;
this._postBackReference=null;
this._onClickDelegate=null;
this._webServiceSettings=new a.WebServiceSettings({});
this._persistLoadOnDemandItems=true;
this._enableOverlay=true;
this._childListElementCssClass="";
this._selectedItemIndex=null;
this._enabled=true;
this._visible=true;
this._openedItem=null;
this._lastOpenedItem=null;
this._childrenDetached=false;
this._originalZIndex=null;
this._defaultZIndex=7000;
this._zIndexIncrementDepth=0;
this._fireEvents=true;
this._webServiceLoader=null;
this._loadingTemplate="";
this._onMouseOutDelegate=null;
this._onClickDelegate=null;
this._onResizeDelegate=null;
this._aboutToCollapse=false;
this._rightToLeft=null;
this._skin=null;
};
a.RadMenu._createChildControls=function(i,k){var j=i.get_itemData();
if(!j){return;
}var l=i.get_childListElement();
if(!l){return;
}e(i._getChildElements()).each(function(m){var n=new a.RadMenuItem();
k.add(n);
n._initialize(j[m],this);
});
};
a.RadMenu._adjustChildrenWidth=function(o,l){var n=o.get_items();
var j=n.get_count();
if(l){for(var k=0;
k<j;
k++){n.getItem(k)._clearWidth();
}}var m=a.RadMenu._getMaxChildWidth(o)+"px";
a.RadMenu._setChildrenWidth(o,m);
};
a.RadMenu._getMaxChildWidth=function(r){var p=0;
var n=r._getControl();
var q=r.get_items();
var j=q.get_count();
for(var k=0;
k<j;
k++){if(n.get_rightToLeft()){var l=q.getItem(k).get_imageElement();
if(l){l.style.styleFloat="left";
l.style.cssFloat="left";
}}var m=q.getItem(k)._getWidth();
p=Math.max(m,p);
}if(r.get_groupSettings){var o=r.get_groupSettings().get_width();
if(o){p=o;
}}return p;
};
a.RadMenu._setChildrenWidth=function(q,m){var n=q._getControl();
var p=q.get_items();
var j=p.get_count();
for(var k=0;
k<j;
k++){if(n.get_rightToLeft()){var l=p.getItem(k).get_imageElement();
if(l){l.style.styleFloat="right";
l.style.cssFloat="right";
}}p.getItem(k)._setWidth(m);
}if($telerik.isSafari){var o=q.get_childListElement();
o.style.width=m;
}};
a.RadMenu._adjustRootItemWidth=function(k,j){var i=$get(k);
var l=a.RadMenu._getMaxRootItemWidth(i,j||null);
a.RadMenu._setRootItemWidth(i,l,j||null);
};
a.RadMenu._getChildListElement=function(i){var j=$telerik.getFirstChildByTagName(i,"ul",0);
if(!j){var k=$telerik.getFirstChildByTagName(i,"div",0);
j=$telerik.getFirstChildByTagName(k,"ul",0);
if(!j){var l=k;
k=$telerik.getFirstChildByTagName(l,"div",0);
j=$telerik.getFirstChildByTagName(k,"ul",0);
}}return j;
};
a.RadMenu._getMaxRootItemWidth=function(o,n){if(!n){n=a.RadMenu._getChildListElement(o);
}var k=n.childNodes;
var j=k.length;
var p=0;
for(var l=0;
l<j;
l++){var q=k[l];
if(q.nodeType===3){continue;
}var m=$telerik.getFirstChildByTagName(q,"a",0);
var r;
if(m){r=m.offsetWidth;
}else{r=q.offsetWidth;
}p=Math.max(p,r);
}return p;
};
a.RadMenu._setRootItemWidth=function(o,s,n){if(!n){n=a.RadMenu._getChildListElement(o);
}var k=n.childNodes;
var j=k.length;
if(s==0){return;
}for(var l=0;
l<j;
l++){var t=k[l];
if(t.nodeType==3){continue;
}var m=$telerik.getFirstChildByTagName(t,"a",0);
if(!m){m=t;
}var r=s;
var p=$telerik.getPaddingBox(m).horizontal;
var q=$telerik.getBorderBox(m).horizontal;
r-=p+q;
var u=m.style.width;
if(!u||r!=u){m.style.width=r+"px";
}}if($telerik.isSafari){n.style.width=s;
}if(o.style.width===""&&a.RadMenu._requiresRightToLeft(o)){o.style.width=s+"px";
}};
a.RadMenu._requiresRightToLeft=function(i){var j=i;
while(j.nodeType!==9){if(j.dir=="rtl"){return true;
}if(e(j).css("direction")=="rtl"){return true;
}j=j.parentNode;
}return false;
};
a.RadMenu._adjustListWidth=function(l,k){var j=l.get_childListElement();
var i=0;
e(".rmItem",j).each(function(){i+=this.offsetWidth;
this.style.clear="none";
});
k=k||0;
k++;
if(i>0){j.style.width=i+"px";
}else{if(k<3){setTimeout(function(){a.RadMenu._adjustListWidth(l,k);
},0);
}}};
a.RadMenu._getViewPortSize=function(){var j=$telerik.getViewPortSize();
var i=document.compatMode!="CSS1Compat";
if($telerik.isFirefox&&i){j.height+=document.body.scrollTop;
}return j;
};
a.RadMenu._updateChildrenPositionClass=function(j){var k=function(l){e("> .rmItem",l).filter(function(){return(this._item&&this._item.get_visible());
}).removeClass("rmFirst rmLast").filter(":first").addClass("rmFirst").end().filter(":last").addClass("rmLast");
};
if(!j){return;
}var i=j.get_childListElement();
if(!i){return;
}if(e(i).is(".rmMultiColumn")){e("> .rmGroupColumn > ul",i).each(function(){k(this);
});
}else{k(i);
}};
a.RadMenu.prototype={initialize:function(){a.RadMenu.callBaseMethod(this,"initialize");
var i=this.get_element();
i.value=this._selectedValue;
if(this.get_rightToLeft()){this._initRightToLeft();
}if(this._flow==a.ItemFlow.Vertical&&this.get_childListElement()){this._adjustRootItemWidth();
}this._originalZIndex=parseInt($telerik.getCurrentStyle(i,"zIndex"));
if(!this._originalZIndex){i.style.zIndex=this._defaultZIndex;
this._originalZIndex=this._defaultZIndex;
}this._onClickDelegate=Function.createDelegate(this,this._onClick);
$addHandler(document,"click",this._onClickDelegate);
if(!this.get_clickToOpen()){if($telerik.isIE){this._onMouseOutDelegate=Function.createDelegate(this,this._onMouseOut);
$addHandler(document,"mouseout",this._onMouseOutDelegate);
}}this._onResizeDelegate=Function.createDelegate(this,this._onResize);
$addHandler(window,"resize",this._onResizeDelegate);
this._eventMap.addHandlerForClassName("mouseover",c,this._onItemMouseOver);
this._eventMap.addHandlerForClassName("mouseout",c,this._onItemMouseOut);
this._eventMap.addHandlerForClassName("dragstart",c,this._onItemDragStart);
this._eventMap.addHandlerForClassName("click",b,this._onItemClick);
this._eventMap.addHandlerForClassName("click",c,this._onItemClick);
this._eventMap.addHandlerForClassName("mouseover",b,this._onLinkMouseOver);
this._eventMap.addHandlerForClassName("mouseout",b,this._onLinkMouseOut);
this._eventMap.addHandlerForClassName("mousedown",b,this._onLinkMouseDown);
this._eventMap.addHandlerForClassName("mouseup",b,this._onLinkMouseUp);
this._eventMap.addHandlerForClassName("blur",b,this._onLinkBlur);
this._eventMap.addHandlerForClassName("deactivate",b,this._onLinkBlur);
this._eventMap.addHandlerForClassName("focus",b,this._onLinkFocus);
this._eventMap.addHandlerForClassName("activate",b,this._onLinkFocus);
this._eventMap.addHandlerForClassName("keydown",b,this._onLinkKeyDown);
this._eventMap.addHandlerForClassName("mousedown",d,this._onTopArrowMouseDown);
this._eventMap.addHandlerForClassName("mouseup",d,this._onTopArrowMouseUp);
this._eventMap.addHandlerForClassName("mouseover",d,this._onTopArrowMouseOver);
this._eventMap.addHandlerForClassName("mouseout",d,this._onTopArrowMouseOut);
this._eventMap.addHandlerForClassName("click",d,this._onScrollArrowClicked);
this._eventMap.addHandlerForClassName("mousedown",g,this._onBottomArrowMouseDown);
this._eventMap.addHandlerForClassName("mouseup",g,this._onBottomArrowMouseUp);
this._eventMap.addHandlerForClassName("mouseover",g,this._onBottomArrowMouseOver);
this._eventMap.addHandlerForClassName("mouseout",g,this._onBottomArrowMouseOut);
this._eventMap.addHandlerForClassName("click",g,this._onScrollArrowClicked);
this._eventMap.addHandlerForClassName("mousedown",f,this._onLeftArrowMouseDown);
this._eventMap.addHandlerForClassName("mouseup",f,this._onLeftArrowMouseUp);
this._eventMap.addHandlerForClassName("mouseover",f,this._onLeftArrowMouseOver);
this._eventMap.addHandlerForClassName("mouseout",f,this._onLeftArrowMouseOut);
this._eventMap.addHandlerForClassName("click",f,this._onScrollArrowClicked);
this._eventMap.addHandlerForClassName("mousedown",h,this._onRightArrowMouseDown);
this._eventMap.addHandlerForClassName("mouseup",h,this._onRightArrowMouseUp);
this._eventMap.addHandlerForClassName("mouseover",h,this._onRightArrowMouseOver);
this._eventMap.addHandlerForClassName("mouseout",h,this._onRightArrowMouseOut);
this._eventMap.addHandlerForClassName("click",h,this._onScrollArrowClicked);
this._initializeScroller();
if(!this.get_enabled()){this.set_enabled(false);
}this._raiseEvent("load",null);
},dispose:function(){a.RadMenu.callBaseMethod(this,"dispose");
if(this._onClickDelegate){$removeHandler(document,"click",this._onClickDelegate);
this._onClickDelegate=null;
}if(this._onMouseOutDelegate){$removeHandler(document,"mouseout",this._onMouseOutDelegate);
this._onMouseOutDelegate=null;
}if(this._onResizeDelegate){$removeHandler(window,"resize",this._onResizeDelegate);
this._onResizeDelegate=null;
}if(this._eventMap){this._eventMap.dispose();
this._eventMap=null;
}if(this._scroller){this._scroller.dispose();
this._scroller=null;
}},repaint:function(){var i=this._flow==a.ItemFlow.Vertical;
if(i){this._adjustRootItemWidth();
}var j=this.get_element();
if(this._scroller){var k=this._getScrollWrapElement();
if(i){k.style.height=j.style.height;
}else{k.style.width=j.style.width;
}this._initializeScroller();
}window.setTimeout(function(){j.style.cssText=j.style.cssText;
},0);
},get_items:function(){return this._getChildren();
},set_items:function(i){this._children=i;
},get_enableScreenBoundaryDetection:function(){return this._enableScreenBoundaryDetection;
},set_enableScreenBoundaryDetection:function(i){this._enableScreenBoundaryDetection=i;
},get_enableAutoScroll:function(){return this._enableAutoScroll;
},set_enableAutoScroll:function(i){this._enableAutoScroll=i;
},get_enableSelection:function(){return this._enableSelection;
},set_enableSelection:function(i){this._enableSelection=i;
},get_autoScrollMinimumHeight:function(){return this._autoScrollMinimumHeight;
},set_autoScrollMinimumHeight:function(i){this._autoScrollMinimumHeight=i;
},get_autoScrollMinimumWidth:function(){return this._autoScrollMinimumWidth;
},set_autoScrollMinimumWidth:function(i){this._autoScrollMinimumWidth=i;
},get_childListElement:function(){if(!this._childListElement){var i=this.get_element();
var j=this._getScrollWrapElement();
if(j){i=j;
}this._childListElement=$telerik.getFirstChildByTagName(i,"ul",0);
}return this._childListElement;
},get_expandAnimation:function(){return this._expandAnimation;
},set_expandAnimation:function(j){var i=Sys.Serialization.JavaScriptSerializer.deserialize(j);
this._expandAnimation=new a.AnimationSettings(i);
},get_collapseAnimation:function(){return this._collapseAnimation;
},set_collapseAnimation:function(j){var i=Sys.Serialization.JavaScriptSerializer.deserialize(j);
this._collapseAnimation=new a.AnimationSettings(i);
},get_defaultGroupSettings:function(){return this._defaultGroupSettings;
},set_defaultGroupSettings:function(j){var i=Sys.Serialization.JavaScriptSerializer.deserialize(j);
this._defaultGroupSettings=new a.RadMenuItemGroupSettings(i);
},get_itemData:function(){return this._itemData;
},set_itemData:function(i){this._itemData=i;
},set_enabled:function(j){a.RadMenu.callBaseMethod(this,"set_enabled",[j]);
if(!this.get_isInitialized()){return;
}var m=this.get_element();
var n=this.get_items();
var l=n.get_count();
if(!j){this.disableEvents();
for(var k=0;
k<l;
k++){n.getItem(k).disable();
}}else{this.enableEvents();
for(var k=0;
k<l;
k++){n.getItem(k).enable();
}}},get_focusedItem:function(){return this._focusedItem;
},get_openedItem:function(){return this._openedItem;
},get_clickToOpen:function(){return this._clickToOpen;
},set_clickToOpen:function(i){this._clickToOpen=i;
},get_collapseDelay:function(){return this._collapseDelay;
},set_collapseDelay:function(i){this._collapseDelay=i;
},get_expandDelay:function(){return this._expandDelay;
},set_expandDelay:function(i){this._expandDelay=i;
},get_loadingTemplate:function(){return this._loadingTemplate;
},set_loadingTemplate:function(i){this._loadingTemplate=i;
},get_webServiceSettings:function(){return this._webServiceSettings;
},set_webServiceSettings:function(j){var i=Sys.Serialization.JavaScriptSerializer.deserialize(j);
this._webServiceSettings=new a.WebServiceSettings(i);
},get_rightToLeft:function(){if(this._rightToLeft===null){this._rightToLeft=a.RadMenu._requiresRightToLeft(this.get_element());
}return this._rightToLeft;
},set_rightToLeft:function(i){this._rightToLeft=i;
},set_clicked:function(i){this._clicked=i;
},get_clicked:function(){return this._clicked;
},get_enableRootItemScroll:function(){return this._enableRootItemScroll;
},set_enableRootItemScroll:function(i){this._enableRootItemScroll=i;
},get_selectedItem:function(){if(!this._childControlsCreated){return null;
}if(this._selectedItemIndex){return this._findItemByHierarchicalIndex(this._selectedItemIndex);
}return null;
},get_enableRoundedCorners:function(){return this._enableRoundedCorners;
},set_enableRoundedCorners:function(i){this._enableRoundedCorners=i;
},get_enableShadows:function(){return this._enableShadows;
},set_enableShadows:function(i){this._enableShadows=i;
},saveClientState:function(){var i=this._log._logEntries;
var j={logEntries:i};
if(this._selectedItemIndex){j.selectedItemIndex=this._selectedItemIndex;
}return Sys.Serialization.JavaScriptSerializer.serialize(j);
},close:function(){var i=this.get_openedItem();
if(i){i.close();
}},disable:function(){this.set_enabled(false);
},enable:function(){this.set_enabled(true);
},disableEvents:function(){this._fireEvents=false;
},enableEvents:function(){this._fireEvents=true;
},focus:function(){this.get_element().focus();
},findItemByText:function(i){return this._findItemByText(i);
},findItemByUrl:function(i){return this._findItemByUrl(i);
},findItemByAbsoluteUrl:function(i){return this._findItemByAbsoluteUrl(i);
},findItemByValue:function(i){return this._findItemByValue(i);
},findItemByAttribute:function(i,j){return this._findItemByAttribute(i,j);
},get_allItems:function(){return this._getAllItems();
},get_persistLoadOnDemandItems:function(){return this._persistLoadOnDemandItems;
},set_persistLoadOnDemandItems:function(i){this._persistLoadOnDemandItems=i;
},get_enableOverlay:function(){return this._enableOverlay;
},set_enableOverlay:function(i){this._enableOverlay=i;
},_isMainElementDescendant:function(i){return $telerik.isDescendant(this.get_element(),i);
},_createChildControls:function(){this._children=new a.RadMenuItemCollection(this);
a.RadMenu._createChildControls(this,this._children);
},_createChildListElement:function(){if(!this._childListElementCssClass){return;
}var k=this.get_element();
var j=e("<ul class='"+this._childListElementCssClass+"'></ul>");
var i=e("div.rmScrollWrap",k);
if(i.length==1){j.appendTo(i);
}else{j.appendTo(k);
}},_getChildElements:function(){return e(this.get_childListElement()).children(".rmItem");
},_initializeScroller:function(){if(!this._childControlsCreated){return null;
}var m=this._getScrollWrapElement();
var j=this.get_childListElement();
if(m&&j){var n=null;
if(this._scroller){n=this._scroller.get_currentPosition();
this._scroller.dispose();
}this._scroller=new a.MenuItemScroller(this.get_childListElement(),this._flow);
j.style.display="block";
var i=this._flow==a.ItemFlow.Horizontal;
if(i){a.RadMenu._adjustListWidth(this);
}else{a.RadMenu._adjustChildrenWidth(this);
if(this.get_rightToLeft()&&$telerik.isIE&&j.firstChild){j.style.width=j.firstChild.offsetWidth+"px";
j.parentNode.style.width=j.offsetWidth+"px";
}}this._scroller.initialize();
this._scroller.updateState();
if(n!==null){this._scroller.set_currentPosition(n);
}if(this.get_rightToLeft()&&i){j.style.cssFloat="left";
this._scroller.scrollToMaxPosition();
}if(i&&$telerik.isIE6){var o=this.get_element().offsetHeight+"px";
var k=$telerik.getElementByClassName(this.get_element(),f,"a")||$telerik.getElementByClassName(this.get_element(),"rmLeftArrowDisabled","a");
if(k){k.style.height=o;
}var l=$telerik.getElementByClassName(this.get_element(),h,"a")||$telerik.getElementByClassName(this.get_element(),"rmRightArrowDisabled","a");
if(l){l.style.height=o;
}}}},_getScrollWrapElement:function(){if(!this._scrollWrapElement){var i=$telerik.getFirstChildByTagName(this.get_element(),"div",0);
if(i&&Sys.UI.DomElement.containsCssClass(i,"rmScrollWrap")){this._scrollWrapElement=i;
}}return this._scrollWrapElement;
},_clearSelectedItem:function(){var i=this.get_selectedItem();
if(i){i.set_selected(false);
}},_registerSelectedItem:function(i){this._selectedItemIndex=i._getHierarchicalIndex();
this.updateClientState();
this._updateValidationField(i);
},_unregisterSelectedItem:function(i){if(i._getHierarchicalIndex()!=this._selectedItemIndex){return;
}this._selectedItemIndex=null;
this.updateClientState();
this._updateValidationField(this.get_selectedItem());
},_updateValidationField:function(i){var j="";
if(i){j=i.get_value();
if(j===null){j=i.get_text();
}}this.get_element().value=j;
},_onMouseOut:function(k){var j=k.rawEvent.relatedTarget?k.rawEvent.relatedTarget:k.rawEvent.toElement;
if(!j&&!this._isMainElementDescendant(k.target)){var i=this;
setTimeout(function(){i.close();
},this.get_collapseDelay());
}},_onClick:function(i){if(!this._isMainElementDescendant(i.target)){var j=this.get_clickToOpen();
if(this._focusedItem||j){this.close();
if(this.get_clickToOpen()){this.set_clicked(false);
}}}},_onResize:function(){},_onItemMouseOver:function(l){var k=this._extractItemFromDomElement(l.eventMapTarget);
if(!k.get_enabled()){return true;
}k._preventClose();
if(this.get_clickToOpen()&&!this.get_clicked()){return true;
}if(k._state==a.RadMenuItemState.Open||k._state==a.RadMenuItemState.AboutToOpen){return true;
}var i=k.get_parent();
var j=i.get_openedItem();
if(j&&j!=k){j._clearTimeout();
j._state=a.RadMenuItemState.AboutToClose;
j._setTimeout(function(){j.close();
j._timeoutRef=null;
},this.get_expandDelay());
}if(k.get_items().get_count()==0&&!k._isWebServiceCallNeeded()){return true;
}this._lastOpenedItem=k;
k._state=a.RadMenuItemState.AboutToOpen;
k._setTimeout(function(){k.open();
k._timeoutRef=null;
},this.get_expandDelay());
return true;
},_onItemMouseOut:function(m){var k=this._extractItemFromDomElement(m.eventMapTarget);
if(!k.get_enabled()){return true;
}var l=m.eventMapRelatedTarget;
var i=k.get_element();
if(!l||i==l||$telerik.isDescendant(i,l)){return true;
}if(this._childrenDetached&&$telerik.isDescendant(k.get_parent()._getAnimationContainer(),l)){return true;
}if(this._scroller&&k.get_level()>0&&!$telerik.isDescendant(this.get_element(),l)){var j=k;
while(j.get_level()>0){j=j.get_parent();
}this._onItemMouseOut({eventMapTarget:j.get_element(),eventMapRelatedTarget:l});
}if(k._state==a.RadMenuItemState.Closed||k._state==a.RadMenuItemState.AboutToClose){return true;
}if(k._state==a.RadMenuItemState.AboutToOpen){k._clearTimeout();
k._state=a.RadMenuItemState.Closed;
k.get_parent()._openedItem=null;
return true;
}if(this.get_clickToOpen()){return true;
}k._state=a.RadMenuItemState.AboutToClose;
k._setTimeout(function(){k.close();
k._timeoutRef=null;
},this._collapseDelay);
return true;
},_onItemDragStart:function(i){i.preventDefault();
return false;
},_getFirstClickableParent:function(i,m){var j=["select","option","a","input","textarea","button"];
var l=i;
while(l!=m){var k=e.inArray(l.tagName.toLowerCase(),j)!=-1;
if(k){return l;
}l=l.parentNode;
}return null;
},_onItemClick:function(k){if(!this.get_enabled()){$telerik.cancelRawEvent(k);
return false;
}var j=this._extractItemFromDomElement(k.eventMapTarget);
var i=this._getFirstClickableParent(k.target,j.get_element());
if(i&&!e(i).hasClass(b)){return true;
}if(e(k.eventMapTarget).is(".rmItem")&&j.get_linkElement()){return true;
}j._click(k);
if(!j._shouldNavigate()){$telerik.cancelRawEvent(k);
return false;
}return true;
},_onLinkMouseOver:function(l){var k=l.eventMapRelatedTarget;
var j=this._extractItemFromDomElement(l.eventMapTarget);
if(!j.get_enabled()){return true;
}var i=j.get_linkElement();
if(!k||i==k||$telerik.isDescendant(i,k)){return true;
}j._hovered=true;
j._updateImageSrc();
this._raiseEvent("mouseOver",new a.RadMenuMouseOverEventArgs(j,l));
return true;
},_onLinkMouseOut:function(l){var k=l.eventMapRelatedTarget;
var j=this._extractItemFromDomElement(l.eventMapTarget);
if(!j.get_enabled()){return true;
}var i=j.get_linkElement();
if(!k||!i){return;
}if(i==k||$telerik.isDescendant(i,k)){return true;
}j._hovered=false;
j._updateImageSrc();
this._raiseEvent("mouseOut",new a.RadMenuMouseOutEventArgs(j,l));
return true;
},_onLinkMouseDown:function(i){var j=this._extractItemFromDomElement(i.eventMapTarget);
if(!j.get_enabled()){return true;
}j._clicked=true;
j._updateLinkClass();
j._updateImageSrc();
return true;
},_onLinkMouseUp:function(i){var j=this._extractItemFromDomElement(i.eventMapTarget);
if(!j.get_enabled()){return true;
}j._clicked=false;
j._updateLinkClass();
j._updateImageSrc();
return true;
},_onLinkBlur:function(i){var j=this._extractItemFromDomElement(i.eventMapTarget);
if(!j.get_enabled()){return true;
}j._focused=false;
j.blur();
return true;
},_onLinkFocus:function(i){var j=this._extractItemFromDomElement(i.eventMapTarget);
if(!j.get_enabled()){return true;
}j._focused=true;
j.focus();
return true;
},_onLinkKeyDown:function(i){var j=this._extractItemFromDomElement(i.eventMapTarget);
if(!j.get_enabled()){return true;
}return j._onKeyDown(i);
},_getScrollItem:function(i){if(this._scroller&&Sys.UI.DomElement.containsCssClass(i.parentNode,"rmRootGroup")){return this;
}return this._extractItemFromDomElement(i);
},_onTopArrowMouseDown:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseDown(a.ArrowPosition.Top);
},_onTopArrowMouseUp:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseUp(a.ArrowPosition.Top);
},_onTopArrowMouseOver:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseOver(a.ArrowPosition.Top);
},_onTopArrowMouseOut:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseOut(a.ArrowPosition.Top);
},_onBottomArrowMouseDown:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseDown(a.ArrowPosition.Bottom);
},_onBottomArrowMouseUp:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseUp(a.ArrowPosition.Bottom);
},_onBottomArrowMouseOver:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseOver(a.ArrowPosition.Bottom);
},_onBottomArrowMouseOut:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseOut(a.ArrowPosition.Bottom);
},_onLeftArrowMouseDown:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseDown(a.ArrowPosition.Left);
},_onLeftArrowMouseUp:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseUp(a.ArrowPosition.Left);
},_onLeftArrowMouseOver:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseOver(a.ArrowPosition.Left);
},_onLeftArrowMouseOut:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseOut(a.ArrowPosition.Left);
},_onRightArrowMouseDown:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseDown(a.ArrowPosition.Right);
},_onRightArrowMouseUp:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseUp(a.ArrowPosition.Right);
},_onRightArrowMouseOver:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseOver(a.ArrowPosition.Right);
},_onRightArrowMouseOut:function(i){var j=this._getScrollItem(i.eventMapTarget);
j._onScrollArrowMouseOut(a.ArrowPosition.Right);
},_onScrollArrowClicked:function(i){i.preventDefault();
i.stopPropagation();
return false;
},_onScrollArrowMouseDown:function(){if(!this._scroller){return;
}this._scroller.changeScrollSpeed(a.ScrollerSpeed.Fast);
},_onScrollArrowMouseUp:function(){if(!this._scroller){return;
}this._scroller.changeScrollSpeed(a.ScrollerSpeed.Slow);
},_onScrollArrowMouseOver:function(k){if(!this._scroller){return;
}var i=1;
if(k==a.ArrowPosition.Top||k==a.ArrowPosition.Left){i=-1;
}var j=this.get_openedItem();
if(j){j.close();
}this._scroller.startScroll(a.ScrollerSpeed.Slow,i);
},_onScrollArrowMouseOut:function(){if(!this._scroller){return;
}this._scroller.stopScroll();
},_childrenCleared:function(i){if(i._slideWrapElement){i._slideWrapElement.outerHTML="";
i._slideWrapElement=null;
i._scrollWrapElement=null;
}i._linkElement=null;
i._childListElement=null;
i._animatedElement=null;
i._animationContainer=null;
i._itemsLoaded=false;
i._hasItems=false;
if(i._originalExpandMode){i.set_expandMode(i._originalExpandMode);
}if(i._updateTextElementClass){i._updateTextElementClass();
}if(i==this){this.close();
}a.RadMenu.callBaseMethod(this,"_childrenCleared",[i]);
},_childInserting:function(j,k,i){a.RadMenu.callBaseMethod(this,"_childInserting",[j,k,i]);
if(!i._childControlsCreated){return;
}this._backupClientState();
},_childInserted:function(j,k,i){this._restoreClientState();
if(i._setHasItems){i._setHasItems(true);
}a.RadMenu.callBaseMethod(this,"_childInserted",[j,k,i]);
if(i._updateTextElementClass){i._updateTextElementClass();
}if(i._state&&i._state==a.RadMenuItemState.Open){if(k._getWidth()>0){a.RadMenu._adjustChildrenWidth(i);
}i._updateColumnWrapSize();
}if(i==this&&this._enableRootItemScroll){this._initializeScroller();
}},_attachChildItem:function(n,m,i){if(i==this||!i._hasMultipleColumns()){a.RadMenu.callBaseMethod(this,"_attachChildItem",[n,m,i]);
return;
}if(!i.get_childListElement()){i._createChildListElement();
}var l=n.get_nextSibling();
if(l){var j=l.get_element();
j.parentNode.insertBefore(m,j);
}else{var k=i._getColumnForItem(n);
e("> .rmGroup",k).append(m);
i._recalculateColumns();
}},_childRemoving:function(i){i.set_selected(false);
this._backupClientState();
a.RadMenu.callBaseMethod(this,"_childRemoving",[i]);
},_childRemoved:function(k,i){this._restoreClientState();
k.get_text();
var j=k.get_element();
if(i.get_items().get_count()==0){if(i._slide){i._slide.dispose();
i._slide=null;
}j=$telerik.getFirstChildByTagName(i.get_element(),"div",0);
i._linkElement=null;
i._childListElement=null;
i._scrollWrapElement=null;
i._slideWrapElement=null;
i._animatedElement=null;
i._animationContainer=null;
i._hasItems=false;
if(i._updateTextElementClass){i._updateTextElementClass();
}}if(j){j.outerHTML="";
if(j.parentNode){j.parentNode.removeChild(j);
}j=null;
}a.RadMenu.callBaseMethod(this,"_childRemoved",[k,i]);
if(i._state&&i._state==a.RadMenuItemState.Open){a.RadMenu._adjustChildrenWidth(i,true);
i._updateColumnWrapSize();
}if(i==this&&this._enableRootItemScroll){this._initializeScroller();
}a.RadMenu._updateChildrenPositionClass(i);
},_backupClientState:function(){this._backupSelectedItem=this.get_selectedItem();
},_restoreClientState:function(){if(this._backupSelectedItem){this._registerSelectedItem(this._backupSelectedItem);
}},_getExtendedItemClickingEventArgs:function(i){return i;
},_getExtendedItemClickedEventArgs:function(i){return i;
},_incrementZIndex:function(j){if(this._zIndexIncrementDepth==0){var i=this.get_element();
i.style.zIndex=this._originalZIndex+j;
}this._zIndexIncrementDepth++;
},_restoreZIndex:function(){if(this._zIndexIncrementDepth>0){this._zIndexIncrementDepth--;
}if(this._zIndexIncrementDepth==0){var i=this.get_element();
i.style.zIndex=this._originalZIndex;
}},_getRtlClassName:function(){return"RadMenu_rtl";
},_getMainElement:function(){return this.get_element();
},_initRightToLeft:function(){var m=this._getMainElement();
m.dir="ltr";
if(m.className.indexOf("RadMenu_rtl")<0||m.className.indexOf("RadMenu_Context_rtl")<0){m.className=String.format("{0} {1}",m.className,this._getRtlClassName());
if(this._skin){m.className=String.format("{0} RadMenu_{1}_rtl",m.className,this._skin);
}}for(var k=0;
k<this.get_items().get_count();
k++){var j=this.get_items().getItem(k);
var n=j.get_imageElement();
var l=j.get_linkElement();
if(n&&l){n.style.styleFloat="left";
n.style.cssFloat="left";
l.style.width=j._getWidth()+"px";
n.style.styleFloat="right";
n.style.cssFloat="right";
}}},_postback:function(j){if(!this._postBackReference){return;
}var i=this._postBackReference.replace("arguments",j);
eval(i);
},_raiseEvent:function(i,j){if(this._fireEvents){this.raiseEvent(i,j);
}},_initializeWebServiceLoader:function(){this._webServiceLoader=new a.WebServiceLoader(this.get_webServiceSettings());
this._webServiceLoader.add_loadingStarted(Function.createDelegate(this,this._onItemLoadingStarted));
this._webServiceLoader.add_loadingSuccess(Function.createDelegate(this,this._onItemLoadingSuccess));
this._webServiceLoader.add_loadingError(Function.createDelegate(this,this._onItemLoadingError));
},_loadChildrenFromWebService:function(l){if(!this._webServiceLoader){this._initializeWebServiceLoader();
}var m={};
var j=new a.RadMenuItemPopulatingEventArgs(l,m);
this._raiseEvent("itemPopulating",j);
if(j.get_cancel()){return;
}var i={Text:l.get_text(),Value:l.get_value(),ExpandMode:l.get_expandMode()};
if(l.get_attributes().get_count()>0){i.Attributes=l.get_attributes()._data;
}var k={item:i,context:m};
if(this.get_webServiceSettings().get_isWcf()){k.context=this._webServiceLoader._serializeDictionaryAsKeyValuePairs(k.context);
if(k.item.Attributes){k.item.Attributes=this._webServiceLoader._serializeDictionaryAsKeyValuePairs(k.item.Attributes);
}}this._webServiceLoader.loadData(k,l);
},_onItemLoadingStarted:function(i,k){var j=k.get_context();
j._onChildrenLoading();
},_onItemLoadingSuccess:function(p,q){var r=q.get_data();
var t=q.get_context();
var s=t.get_items();
var o=this.get_webServiceSettings().get_isWcf();
for(l=0;
l<r.length;
l++){var m=r[l];
var k=new a.RadMenuItem();
k._loadFromDictionary(m,o);
if(k.get_navigateUrl()===""){k.set_navigateUrl("#");
}s.add(k);
}t._onChildrenLoaded();
if(this.get_persistLoadOnDemandItems()){this.trackChanges();
t.set_expandMode(a.MenuItemExpandMode.ClientSide);
var j=s.get_count();
for(var l=0;
l<j;
l++){this._log.logInsert(s.getItem(l));
}this.commitChanges();
}var n=new a.RadMenuItemPopulatedEventArgs(t);
this._raiseEvent("itemPopulated",n);
},_onItemLoadingError:function(i,m){var j=m.get_message();
var l=m.get_context();
l._onChildrenLoadingError();
var k=new a.RadMenuItemPopulationFailedEventArgs(l,j);
this._raiseEvent("itemPopulationFailed",k);
if(k.get_cancel()){return;
}alert(j);
},_adjustRootItemWidth:function(){a.RadMenu._adjustRootItemWidth(this.get_id(),this.get_childListElement());
},add_mouseOver:function(i){this.get_events().addHandler("mouseOver",i);
},remove_mouseOver:function(i){this.get_events().removeHandler("mouseOver",i);
},add_mouseOut:function(i){this.get_events().addHandler("mouseOut",i);
},remove_mouseOut:function(i){this.get_events().removeHandler("mouseOut",i);
},add_itemFocus:function(i){this.get_events().addHandler("itemFocus",i);
},remove_itemFocus:function(i){this.get_events().removeHandler("itemFocus",i);
},add_itemBlur:function(i){this.get_events().addHandler("itemBlur",i);
},remove_itemBlur:function(i){this.get_events().removeHandler("itemBlur",i);
},add_itemClicking:function(i){this.get_events().addHandler("itemClicking",i);
},remove_itemClicking:function(i){this.get_events().removeHandler("itemClicking",i);
},add_itemClicked:function(i){this.get_events().addHandler("itemClicked",i);
},remove_itemClicked:function(i){this.get_events().removeHandler("itemClicked",i);
},add_itemOpening:function(i){this.get_events().addHandler("itemOpening",i);
},remove_itemOpening:function(i){this.get_events().removeHandler("itemOpening",i);
},add_itemOpened:function(i){this.get_events().addHandler("itemOpened",i);
},remove_itemOpened:function(i){this.get_events().removeHandler("itemOpened",i);
},add_itemClosing:function(i){this.get_events().addHandler("itemClosing",i);
},remove_itemClosing:function(i){this.get_events().removeHandler("itemClosing",i);
},add_itemClosed:function(i){this.get_events().addHandler("itemClosed",i);
},remove_itemClosed:function(i){this.get_events().removeHandler("itemClosed",i);
},add_load:function(i){this.get_events().addHandler("load",i);
},remove_load:function(i){this.get_events().removeHandler("load",i);
},add_itemPopulating:function(i){this.get_events().addHandler("itemPopulating",i);
},remove_itemPopulating:function(i){this.get_events().removeHandler("itemPopulating",i);
},add_itemPopulated:function(i){this.get_events().addHandler("itemPopulated",i);
},remove_itemPopulated:function(i){this.get_events().removeHandler("itemPopulated",i);
},add_itemPopulationFailed:function(i){this.get_events().addHandler("itemPopulationFailed",i);
},remove_itemPopulationFailed:function(i){this.get_events().removeHandler("itemPopulationFailed",i);
}};
a.RadMenu.registerClass("Telerik.Web.UI.RadMenu",a.ControlItemContainer);
})();
(function(l){Type.registerNamespace("Telerik.Web.UI");
var b=Telerik.Web.UI,m=Telerik.Web.StringBuilder;
l.registerEnum(b,"RadMenuItemState",{Closed:0,Open:1,AboutToClose:2,AboutToOpen:3});
l.registerEnum(b,"MenuItemExpandMode",{ClientSide:0,WebService:1});
var q="rmGroup",d="rmMultiColumn",e="rmGroupColumn",c="rmFirstGroupColumn",g="rmScrollWrap",a="rmLevel",r="rmHorizontal",f="rmVertical",o="rmLink",p="rmLeftImage",k="rmDisabled",j="rmExpanded",n="rmFocused",i="rmSelected",h="rmClicked";
b.RadMenuItem=function(){b.RadMenuItem.initializeBase(this);
this._zIndexStep=1000;
this._defaultScrollSize=16;
this._menu=null;
this._groupSettings=new b.RadMenuItemGroupSettings({});
this._imageUrl=null;
this._flow=null;
this._openedItem=null;
this._timeoutRef=null;
this._focused=false;
this._clicked=false;
this._hovered=false;
this._isImageOnly=null;
this._itemsLoaded=false;
this._itemsLoading=false;
this._adjustSiblingsWidthOnShow=false;
this._state=b.RadMenuItemState.Closed;
this._linkElement=null;
this._imageElement=null;
this._childListElement=null;
this._scrollWrapElement=null;
this._slideWrapElement=null;
this._animatedElement=null;
this._animationContainer=null;
this._childrenDetached=false;
this._autoScrollActive=false;
this._animationContainerOriginalSize=null;
this._collapseAnimationEndedDelegate=null;
this._slide=null;
this._scroller=null;
this._styleCssText=null;
this._hasItems=null;
};
b.RadMenuItem.prototype={_initialize:function(s,u){b.RadMenuItem.callBaseMethod(this,"_initialize",[s,u]);
var t=this.get_menu();
this._groupSettings=new b.RadMenuItemGroupSettings(s.groupSettings||{},t.get_defaultGroupSettings());
this._initializeAnimation();
this._clearNavigateUrl();
this._updateTextElementClass();
this._renderAccessKey();
this._originalExpandMode=this.get_expandMode();
},_dispose:function(){b.RadMenuItem.callBaseMethod(this,"_dispose");
if(this._collapseAnimationEndedDelegate){if(this._slide){this._slide.remove_collapseAnimationEnded(this._collapseAnimationEndedDelegate);
}this._collapseAnimationEndedDelegate=null;
}if(this._slide){this._slide.dispose();
this._slide=null;
}if(this._scroller){this._scroller.dispose();
this._scroller=null;
}var s=this._getAnimationContainer();
if(s){s._item=null;
s._itemTypeName=null;
}this._childListElement=null;
this._clearTimeout();
},_initializeRenderedItem:function(){b.RadMenuItem.callBaseMethod(this,"_initializeRenderedItem");
this._initializeAnimation();
this._clearNavigateUrl();
this._updateTextElementClass();
this._updateLinkClass();
this._renderAccessKey();
b.RadMenu._updateChildrenPositionClass(this.get_parent());
b.RadMenu._updateChildrenPositionClass(this);
},get_linkElement:function(){if(!this._linkElement){this._linkElement=$telerik.getFirstChildByTagName(this.get_element(),"a",0);
}return this._linkElement;
},get_childListElement:function(){if(!this._childListElement){var u=this._getSlideWrapElement();
if(u){var s=u;
var t=this._getScrollWrapElement();
if(t){s=t;
}this._childListElement=$telerik.getFirstChildByTagName(s,"ul",0);
}}return this._childListElement;
},get_imageElement:function(){if(!this._imageElement){var t=this.get_linkElement();
var s=this.get_element();
this._imageElement=$telerik.getFirstChildByTagName(t||s,"img",0);
}return this._imageElement;
},get_textElement:function(){var s=this.get_linkElement();
if(s){return $telerik.getChildByClassName(s,"rmText",0);
}else{return null;
}},get_menu:function(){return this._getControl();
},get_items:function(){return this._getChildren();
},set_text:function(s){b.RadMenuItem.callBaseMethod(this,"set_text",[s]);
if(this._state!=b.RadMenuItemState.Closed){this._clearWidth();
this._setWidth(this._getWidth()+"px");
}else{if(this._getParentFlow()==b.ItemFlow.Vertical){this._adjustSiblingsWidthOnShow=true;
}}},get_navigateUrl:function(){var s=this.get_linkElement();
if(!this.get_enabled()&&s){return l(s).data("href");
}else{return this._getNavigateUrl();
}},set_navigateUrl:function(s){this._properties.setValue("navigateUrl",s,true);
if(this.get_linkElement()){this.get_linkElement().href=s;
}this._clearNavigateUrl();
},get_target:function(){return this._properties.getValue("target",null);
},set_target:function(s){this._properties.setValue("target",s);
if(this.get_linkElement()){this.get_linkElement().target=s;
}},get_groupSettings:function(){return this._groupSettings;
},set_groupSettings:function(s){this._groupSettings=s;
},get_isOpen:function(){if(this.get_parent()){return this.get_parent().get_openedItem()==this;
}return false;
},_getNextItem:function(){var t=this.get_parent().get_items();
var s=this.get_index();
if(s==t.get_count()-1){return t.getItem(0);
}return t.getItem(s+1);
},_getPreviousItem:function(){var t=this.get_parent().get_items();
var s=this.get_index();
if(s==0){return t.getItem(t.get_count()-1);
}return t.getItem(s-1);
},_focus:function(s){this._setFocused(true,s);
},_blur:function(s){this._setFocused(false,s);
},_setFocused:function(t,s){if(t){this._doFocus(s);
}else{this._doBlur(s);
}this._focused=t;
this._updateLinkClass();
},_open:function(u){var s=this.get_menu();
var t=new b.RadMenuItemOpeningEventArgs(this,u);
s._raiseEvent("itemOpening",t);
if(t.get_cancel()){return;
}if(this._isWebServiceCallNeeded()){this._loadChildrenFromWebService();
return;
}this._doOpen(u);
},_close:function(w){if(this.get_isSeparator()||this._state==b.RadMenuItemState.Closed){return;
}var v=new b.RadMenuItemClosingEventArgs(this,w);
this.get_menu()._raiseEvent("itemClosing",v);
if(v.get_cancel()){return;
}if(this._openedItem){this._openedItem._close(w);
}var s=this.get_parent();
s._openedItem=null;
if(!this._getAnimationContainer()){return;
}this._state=b.RadMenuItemState.Closed;
var t=this.get_menu();
if(this.get_level()==0){t._aboutToCollapse=true;
}if(!this._getIsImageOnly()){this.get_element().style.zIndex=0;
}this._slide.collapse();
this._updateLinkClass();
this._updateImageSrc();
var u=new b.RadMenuItemClosedEventArgs(this,w);
this.get_menu()._raiseEvent("itemClosed",u);
this._closeChildren(w);
},get_nextItem:function(){return this.get_nextSibling();
},get_previousItem:function(){return this.get_previousSibling();
},get_focusedItem:function(){return this._focusedItem;
},get_isSeparator:function(){return this._properties.getValue("isSeparator",false);
},set_isSeparator:function(s){this._properties.setValue("isSeparator",s,true);
},get_openedItem:function(){return this._openedItem;
},get_templated:function(){return this._properties.getValue("templated",false)==true;
},get_cssClass:function(){return this._properties.getValue("cssClass","");
},set_cssClass:function(s){this._properties.setValue("cssClass",s,true);
},get_focused:function(){return this._focused;
},set_focused:function(s){this._setFocused(s);
},get_selected:function(){return this._properties.getValue("selected",false)==true;
},set_selected:function(t){if(!this.get_enabled()&&t){return;
}if(this.get_selected()==t){return;
}this._properties.setValue("selected",t);
var s=this.get_menu();
if(!s){return;
}if(t){s._clearSelectedItem();
s._registerSelectedItem(this);
}else{s._unregisterSelectedItem(this);
}this._updateImageSrc();
this._updateLinkClass();
},get_hoveredImageUrl:function(){return this._properties.getValue("hoveredImageUrl",null);
},set_hoveredImageUrl:function(s){this._properties.setValue("hoveredImageUrl",s,true);
this._updateImageSrc();
},get_clickedImageUrl:function(){return this._properties.getValue("clickedImageUrl",null);
},set_clickedImageUrl:function(s){this._properties.setValue("clickedImageUrl",s,true);
this._updateImageSrc();
},get_selectedImageUrl:function(){return this._properties.getValue("selectedImageUrl",null);
},set_selectedImageUrl:function(s){this._properties.setValue("selectedImageUrl",s,true);
this._updateImageSrc();
},get_imageUrl:function(){if(this._imageUrl){return this._imageUrl;
}if(this._imageUrl=this._properties.getValue("imageUrl",null)){return this._imageUrl;
}this._imageUrl=this._getCurrentImageUrl();
return this._imageUrl;
},_getCurrentImageUrl:function(){var t=null;
var s=this.get_imageElement();
if(s){t=s.src;
}return t;
},set_imageUrl:function(s){this._imageUrl=s;
this._properties.setValue("imageUrl",s,true);
if(!s){l(this.get_imageElement()).remove();
this._imageElement=null;
return;
}this._updateImageSrc();
},set_visible:function(s){var x=this.get_visible()!=s;
if(!x){return;
}b.RadMenuItem.callBaseMethod(this,"set_visible",[s]);
if(this._getParentFlow()==b.ItemFlow.Vertical){this._adjustSiblingsWidthOnShow=true;
}this._clearWidth();
var y=s?"":"none";
var u=this.get_linkElement();
var v=this.get_textElement();
var z;
if(u){z=u;
}else{if(v){z=v;
}}if(this.get_isSeparator()||this.get_templated()){z=this.get_element().childNodes[0];
}z.style.display=y;
if(this.get_visible()){this.get_element().style.cssText=this._styleCssText;
}else{this._styleCssText=this.get_element().style.cssText;
this.get_element().style.cssText="padding:0px;margin:0px;height:0px;overflow:hidden;";
}var w=this._getParentFlow();
if(w==b.ItemFlow.Vertical){if(!s){this._clearSiblingsWidth();
}var t=this.get_parent();
if(t.get_element().offsetWidth>0){b.RadMenu._adjustChildrenWidth(t);
}}},get_expandedImageUrl:function(){return this._properties.getValue("expandedImageUrl",null);
},set_expandedImageUrl:function(s){this._properties.setValue("expandedImageUrl",s,true);
this._updateImageSrc();
},get_disabledImageUrl:function(){return this._properties.getValue("disabledImageUrl",null);
},set_disabledImageUrl:function(s){this._properties.setValue("disabledImageUrl",s,true);
this._updateImageSrc();
},get_disabledCssClass:function(){return this._properties.getValue("disabledCssClass",k);
},set_disabledCssClass:function(s){this._properties.setValue("disabledCssClass",s,true);
this._updateLinkClass();
},get_expandedCssClass:function(){return this._properties.getValue("expandedCssClass",j);
},set_expandedCssClass:function(s){this._properties.setValue("expandedCssClass",s,true);
this._updateLinkClass();
},get_focusedCssClass:function(){return this._properties.getValue("focusedCssClass",n);
},set_focusedCssClass:function(s){this._properties.setValue("focusedCssClass",s,true);
this._updateLinkClass();
},get_selectedCssClass:function(){return this._properties.getValue("selectedCssClass",i);
},set_selectedCssClass:function(s){this._properties.setValue("selectedCssClass",s,true);
this._updateLinkClass();
},get_clickedCssClass:function(){return this._properties.getValue("clickedCssClass",h);
},set_clickedCssClass:function(s){this._properties.setValue("clickedCssClass",s,true);
this._updateLinkClass();
},get_postBack:function(){return this._properties.getValue("postBack",true)==true;
},set_postBack:function(s){this._properties.setValue("postBack",s);
},get_expandMode:function(){return this._properties.getValue("expandMode",b.MenuItemExpandMode.ClientSide);
},set_expandMode:function(s){this._properties.setValue("expandMode",s,true);
},set_enabled:function(s){b.RadMenuItem.callBaseMethod(this,"set_enabled",[s]);
this._updateLinkClass();
this._updateImageSrc();
if(s){this._restoreNavigateUrl();
}else{this._clearNavigateUrl();
}},get_level:function(){var s=this.get_parent();
var t=0;
while(s){if(b.ControlItemContainer.isInstanceOfType(s)||b.RadMenu.isInstanceOfType(s)){return t;
}t++;
s=s.get_parent();
}return t;
},open:function(){this._open(null);
},close:function(){this._close(null);
},hide:function(){this.set_visible(false);
},show:function(){this.set_visible(true);
},focus:function(){this._setFocused(true,null);
},blur:function(){this._blur(null);
},focusFirstChild:function(v){var u=this.get_items();
if(u.get_count()==0){return;
}var t=u.getItem(0);
var s=t;
while(!t._canFocus()){t=t._getNextItem();
if(t==s){return;
}}t._focus(v||null);
},focusLastChild:function(v){var u=this.get_items();
if(u.get_count()==0){return;
}var t=u.getItem(u.get_count()-1);
var s=t;
while(!t._canFocus()){t=t._getPreviousItem();
if(t==s){return;
}}t._focus(v||null);
},focusNextItem:function(s){var t=this._getNextItem();
while(!t._canFocus()){t=t._getNextItem();
}t._focus(s||null);
},focusPreviousItem:function(s){var t=this._getPreviousItem();
while(!t._canFocus()){t=t._getPreviousItem();
}t._focus(s||null);
},select:function(){this.set_selected(true);
this.click();
},unselect:function(){this.set_selected(false);
},disable:function(){this.set_enabled(false);
},enable:function(){this.set_enabled(true);
},click:function(){this._click(null);
},_determineCssClass:function(){if(this.get_isSeparator()){return"rmItem rmSeparator";
}return"rmItem";
},_renderImage:function(s){var t=new m(s).append("<img alt='' src='",this.get_imageUrl(),"' ").append("class='",p,"' ");
if(!this.get_enabled()){t.append("disabled='disabled'");
}t.append("/>");
return s;
},_renderLink:function(u){if(this.get_isSeparator()){return;
}var v="#";
var w=this.get_navigateUrl();
if(w&&w!="#"){v=w;
}var t=new m(u);
t.append("<a href='",v,"' ");
var s=this.get_target();
if(s){t.append("target='",s,"' ");
}t.append("class='",o," ");
if(!this.get_enabled()){t.append(k);
}t.append("'>");
},_renderChildItems:function(t,s){var v=this.get_items().toArray();
if(!s&&v.length==0){return;
}var w=new m(t);
w.append("<div class='rmSlide'>");
if(this._getShouldRenderScrollWrap()){this._renderScrollWrap(w);
}var u=this._getGroupCssClass();
if(this._hasMultipleColumns()){this._renderColumns(w,v,u,s);
}else{this._renderChildGroup(w,v,u,s);
}if(this._getShouldRenderScrollWrap()){w.append("</div>");
}w.append("</div>");
},_renderScrollWrap:function(u){u.append("<div class='").append(g," ",q," ").append(a,this._getGroupLevelCssClass()).append("' style='");
var s=this.get_groupSettings();
var t=s.get_width();
if(t){u.append("width :",t,";");
}var v=s.get_height();
if(v){u.append("height :",v,";");
}u.append("'>");
},_renderColumns:function(z,A,y,C){z.append("<ul class='",d,"'>");
var u=this.get_groupSettings();
var w=u.get_repeatColumns();
var v=C?0:Math.min(w,A.length);
var B=u.get_repeatDirection();
for(var t=0;
t<v;
t++){var x="";
if(t==0){var x=" "+c;
}z.append("<li class='",e,x,"'>");
var s=B==b.MenuRepeatDirection.Vertical?this._getRowItems(t,w,A):this._getColumnItems(t,w,A);
this._renderChildGroup(z,s,y);
z.append("</li>");
}z.append("</ul>");
},_renderChildGroup:function(t,v,u,s){t.append("<ul class='",u,"'>");
if(!s){l.each(v,function(){this._render(t.get_buffer());
});
}t.append("</ul>");
},_getGroupLevelCssClass:function(){return a+(this.get_level()+1);
},_getGroupCssClass:function(){var s=new m();
s.append(this._getFlowCssClass());
if(!this._getShouldRenderScrollWrap()){s.append(" ",q," ",this._getGroupLevelCssClass());
}return s.toString();
},_getRowItems:function(x,v,w){var u=[];
for(var t=0;
t<v;
t++){u[t]=[];
}var s=function(){for(var z=u.length-1;
z>0;
z--){var B=u[z];
var A=u[z-1];
if(B.length==A.length){return;
}A.push(B.shift());
}};
var y=u[v-1];
l.each(w,function(){y.push(this);
s();
});
return u[x];
},_getColumnItems:function(s,t,w){var x=[];
var v=0;
for(var u=0;
u<w.length;
u++){if(v==s){x.push(w[u]);
}v=(v+1)%t;
}return x;
},_doOpen:function(x){var w=this.get_menu();
if(this.get_items().get_count()==0){return;
}this._ensureChildControls();
var v=this.get_parent();
w._aboutToCollapse=false;
if(v!=w&&v._state!=b.RadMenuItemState.Open){v._open(x);
}var s=this._getAnimationContainer();
if(!s){return;
}v._openedItem=this;
this._state=b.RadMenuItemState.Open;
this._ensureRoundedCorners();
this._ensureShadows();
this._ensureCorners();
var t=this.get_childListElement();
t.style.display="block";
if($telerik.isOpera&&(w.get_enableRoundedCorners()||w.get_enableShadows())){t.style.position="absolute";
}if(!$telerik.isIE7&&!$telerik.isIE6){s.style.visibility="hidden";
}this._updateColumnWrapSize();
this._slide.updateSize();
this._fixSlide();
this._slide.show();
if(this._groupSettings.get_flow()==b.ItemFlow.Vertical){b.RadMenu._adjustChildrenWidth(this);
}else{b.RadMenu._adjustListWidth(this);
}if(this._adjustSiblingsWidthOnShow){this._adjustSiblingsWidth();
this._adjustSiblingsWidthOnShow=false;
}this._updateChildListWidth();
this._resetAnimatedElementPosition();
this._slide.set_direction(this._getSlideDirection());
this._updateScrollWrapSize();
this._updateColumnWrapSize();
this._slide.updateSize();
this._fixSlide();
this._positionChildContainer();
s=this._getAnimationContainer();
if(this._scroller&&!this._autoScrollActive&&!this._fitsWindow()){this._updateScrollSize();
this._positionChildContainer();
}s.style.visibility="visible";
this.get_element().style.zIndex=v.get_items().get_count()-this.get_index();
s.style.zIndex=v.get_items().get_count()+1;
w._incrementZIndex(this._zIndexStep);
if(this._scroller){this._scroller.updateState();
if(this.get_menu().get_rightToLeft()&&this._groupSettings.get_flow()==b.ItemFlow.Horizontal){this.get_childListElement().style.cssFloat="left";
this._scroller.scrollToMaxPosition();
}}this._updateColumnWrapSize();
this._slide.updateSize();
this._fixSlide();
this._slide.expand();
this._updateLinkClass();
this._updateImageSrc();
var u=new b.RadMenuItemOpenedEventArgs(this,x);
this.get_menu()._raiseEvent("itemOpened",u);
},_fixSlide:function(){if($telerik.quirksMode){var s=this._slide.get_element();
s.style.width=parseInt(s.offsetWidth,10)+parseInt($telerik.getCurrentStyle(s,"paddingLeft"),10)+parseInt($telerik.getCurrentStyle(s,"paddingRight"),10);
s.style.height=parseInt(s.offsetHeight,10)+parseInt($telerik.getCurrentStyle(s,"paddingTop"),10)+parseInt($telerik.getCurrentStyle(s,"paddingBottom"),10);
}},_updateChildListWidth:function(){var t=this.get_menu();
if(this._groupSettings.get_flow()==b.ItemFlow.Vertical&&t.get_rightToLeft()&&$telerik.isIE){var u=this.get_childListElement();
var s=l("> .rmItem",u)[0];
if(s){u.style.width=s.offsetWidth+"px";
}}},_shouldInitializeChild:function(){return true;
},_createChildListElement:function(){var s=[];
this._renderChildItems(s,true);
var t=l(s.join(""));
l(this.get_element()).append(t);
this._initializeAnimation();
this._updateTextElementClass();
if(this._getShouldRenderScrollWrap()){this._initializeScroller();
}return t;
},_getColumnForItem:function(x){if(!this._hasMultipleColumns()){return null;
}var u=this.get_childListElement();
var t=l("> .rmGroupColumn",u);
var s=this.get_groupSettings();
var w=s.get_repeatColumns();
if(t.length<w){return this._createEmptyColumn();
}var v=x.get_index();
if(s.get_repeatDirection()==b.MenuRepeatDirection.Horizontal){return t[v%w];
}else{return t[t.length-1];
}},_recalculateColumns:function(){if(this.get_groupSettings().get_repeatDirection()==b.MenuRepeatDirection.Horizontal){return;
}var u=this.get_childListElement();
var t=l("> .rmGroupColumn",u);
for(var s=t.length-1;
s>0;
s--){var w=t[s];
var v=t[s-1];
if(this._getColumnItemCount(v)==this._getColumnItemCount(w)){return;
}l("> .rmGroup",v).append(l("> .rmGroup > .rmItem:first",w));
}},_getColumnItemCount:function(s){return l("> .rmGroup > .rmItem",s).length;
},_createEmptyColumn:function(){var t=this._getGroupCssClass();
var s=new m();
s.append("<li class='",e,"'>");
this._renderChildGroup(s,[],t);
s.append("</li>");
var u=l(s.toString());
l(this.get_childListElement()).append(u);
return u;
},_hasMultipleColumns:function(){var t=this.get_groupSettings();
var s=t.get_repeatColumns();
if(s==1){s=this.get_menu().get_defaultGroupSettings().get_repeatColumns();
}return s>1;
},_getShouldRenderScrollWrap:function(){if(this._hasMultipleColumns()){return false;
}var s=this.get_groupSettings();
var t=this.get_menu().get_defaultGroupSettings();
var v=s.get_width();
if(!v){v=t.get_width();
}var u=s.get_height();
if(!u){u=t.get_height();
}return v||u;
},_getChildElements:function(){var v=l(this.get_childListElement());
if(v.is(".rmMultiColumn")){var z=l("> .rmGroupColumn > ul > .rmItem",v);
var t=this.get_groupSettings();
var y=t.get_repeatDirection();
var u=t.get_repeatColumns();
if(u==1||y==b.MenuRepeatDirection.Vertical){return z;
}var w=[];
var x=Math.ceil(z.length/u);
for(var s=0;
s<x;
s++){z.filter(".rmItem:nth-child("+(s+1)+")").each(function(){Array.add(w,this);
});
}return w;
}else{return v.children(".rmItem");
}},_updateColumnWrapSize:function(){var t=l(this.get_childListElement());
if(!t.is(".rmMultiColumn")){return;
}var s=0;
var u=0;
l("> .rmGroupColumn > .rmGroup",t).each(function(){s+=this.offsetWidth;
u=Math.max(this.offsetHeight,u);
});
if(s==0||u==0){return;
}t.css("width",s+"px").css("height",u+"px");
},_createItemCollection:function(){var s=new b.RadMenuItemCollection(this);
b.RadMenu._createChildControls(this,s);
return s;
},_getSlideWrapElement:function(){if(!this._slideWrapElement){var s=$telerik.getFirstChildByTagName(this.get_element(),"div",1);
if(s&&Sys.UI.DomElement.containsCssClass(s,"rmSlide")){this._slideWrapElement=s;
}}return this._slideWrapElement;
},_getScrollWrapElement:function(){if(!this._scrollWrapElement){var s=this._getSlideWrapElement();
if(s){this._scrollWrapElement=$telerik.getFirstChildByTagName(s,"div",0);
}}return this._scrollWrapElement;
},_getAnimationContainer:function(){if(!this._animationContainer){var s=this.get_templated()?1:0;
this._animationContainer=$telerik.getFirstChildByTagName(this.get_element(),"div",s);
}return this._animationContainer;
},_getAnimatedElement:function(){if(!this._animatedElement){this._animatedElement=this._getScrollWrapElement()||this.get_childListElement();
}return this._animatedElement;
},_determineExpandDirection:function(){var t=this.get_groupSettings();
if(t.get_expandDirection()!=b.ExpandDirection.Auto){return;
}var s=this._getParentFlow();
if(s==b.ItemFlow.Vertical){if(this.get_menu().get_rightToLeft()){t.set_expandDirection(b.ExpandDirection.Left);
}else{t.set_expandDirection(b.ExpandDirection.Right);
}}else{t.set_expandDirection(b.ExpandDirection.Down);
}},_getSlideDirection:function(){var s=this.get_groupSettings().get_expandDirection();
if(s==b.ExpandDirection.Auto){return null;
}return s;
},_getParentFlow:function(){var s=this.get_parent();
if(!s){return null;
}if(s==this.get_menu()){return s._flow;
}else{return s.get_groupSettings().get_flow();
}},_initializeAnimation:function(){this._determineExpandDirection();
var s=this._getAnimatedElement();
if(s){var t=this.get_menu();
this._slide=new b.jSlide(s,t.get_expandAnimation(),t.get_collapseAnimation(),t.get_enableOverlay());
this._slide.initialize();
this._slide.set_direction(this._getSlideDirection());
this._collapseAnimationEndedDelegate=Function.createDelegate(this,this._onCollapseAnimationEnded);
this._slide.add_collapseAnimationEnded(this._collapseAnimationEndedDelegate);
}},_getHasItems:function(){if(this._hasItems===null){this._hasItems=this.get_itemData()&&this.get_itemData().length>0;
}return this._hasItems;
},_setHasItems:function(s){this._hasItems=s;
},_clearNavigateUrl:function(){var s=this.get_linkElement();
if(!s){return;
}if(!this.get_enabled()&&s.href){l(s).data("href",this._getNavigateUrl());
l(s).removeAttr("href");
}},_restoreNavigateUrl:function(){var s=this.get_linkElement();
if(!s){return;
}var t=l(s).data("href");
if(this.get_enabled()&&t){s.href=t;
}},_updateTextElementClass:function(){var t=this.get_textElement();
if(!t){return;
}var s="rmText";
if(this._getHasItems()||this.get_expandMode()==b.MenuItemExpandMode.WebService){s+=" "+this._getExpandClassName();
}t.className=s;
},_onCollapseAnimationEnded:function(){var s=this.get_menu();
this.get_element().style.zIndex=0;
s._restoreZIndex();
if(this.get_level()==0&&s.get_rightToLeft()){var t=s.get_element();
t.style.cssText=t.style.cssText;
}},_initializeScroller:function(){var s=this._getScrollWrapElement();
if(s){this._scroller=new b.MenuItemScroller(this.get_childListElement(),this.get_groupSettings().get_flow());
this._scroller.initialize();
}},_isAutoScrollPossible:function(){var s=this.get_menu();
var t=this._getMaximumExpandSize();
var u=this._getAnimationContainer();
if(this.get_groupSettings().get_flow()==b.ItemFlow.Vertical){return(s._autoScrollMinimumHeight<t&&t<=u.offsetHeight);
}else{return(s._autoScrollMinimumWidth<t&&t<=u.offsetWidth);
}},_fitsWindow:function(){var s=this._getMaximumExpandSize();
var t=this._getAnimationContainer();
if(this.get_groupSettings().get_flow()==b.ItemFlow.Vertical){return t.offsetHeight<=s;
}return t.offsetWidth<=s;
},_getMaximumExpandSize:function(){var x=this._slide.get_direction();
var v=b.RadMenu._getViewPortSize();
var s=this._getAnimationContainer();
var t=$telerik.getLocation(s);
if(this.get_groupSettings().get_flow()==b.ItemFlow.Vertical){var u;
if(x==b.ExpandDirection.Up){u=s.offsetHeight+t.y;
}else{u=v.height-t.y-this._defaultScrollSize;
}return Math.min(u,v.height-this._defaultScrollSize);
}var w;
if(x==b.ExpandDirection.Left){w=t.x;
}else{w=v.width-t.x;
}return Math.min(w,v.width);
},_saveAnimationContainerSize:function(){var u=this._getAnimationContainer();
var t=u.offsetHeight;
var s=u.offsetWidth;
this._animationContainerOriginalSize={};
this._animationContainerOriginalSize.height=t;
this._animationContainerOriginalSize.width=s;
},_restoreAnimationContainerSize:function(){if(this._animationContainerOriginalSize){var s=this._getAnimationContainer();
s.style.height=this._animationContainerOriginalSize.height+"px";
s.style.width=this._animationContainerOriginalSize.width+"px";
this._animationContainerOriginalSize=null;
}},_initializeAutoScroll:function(){this._buildScrollWrap();
this._initializeScroller();
this._animatedElement=null;
this._scrollWrapElement=null;
this._slide.set_animatedElement(this._getAnimatedElement());
},_removeAutoScroll:function(){var w=this.get_items();
var u=w.get_count();
for(var s=0;
s<u;
s++){w.getItem(s)._removeAutoScroll();
}this._attachChildren();
if(!this._scroller){return;
}this._scroller.dispose();
this._scroller=null;
var t=this._getSlideWrapElement();
var x=this.get_childListElement();
var v=this._getScrollWrapElement();
t.appendChild(x);
t.removeChild(v);
x.className=String.format("{0} {1} {2}{3}",this._getFlowCssClass(),q,a,this.get_level());
this._animatedElement=null;
this._scrollWrapElement=null;
this._slide.set_animatedElement(this._getAnimatedElement());
this._slide.updateSize();
},_updateScrollSize:function(){var s=this._slide.get_direction();
var u=this._getAnimationContainer();
var t=this._getScrollWrapElement();
t.style.height="";
t.style.width="";
var v=this._getMaximumExpandSize();
if(this.get_groupSettings().get_flow()==b.ItemFlow.Vertical){$telerik.setSize(t,{height:v,width:parseInt(u.style.width)});
if(s==b.ExpandDirection.Up){u.style.top=-v+"px";
}}else{$telerik.setSize(t,{width:v,height:parseInt(u.style.height)});
}this._slide.updateSize();
this._scroller.resetState();
},_buildScrollWrap:function(){var u=this._getSlideWrapElement();
var s=this.get_childListElement();
var t=document.createElement("div");
t.style.position="relative";
t.style.overflow="hidden";
s.className=this._getFlowCssClass();
t.className=String.format("{0} {1} {2}{3}",g,q,a,this.get_level());
t.appendChild(s);
u.appendChild(t);
},_updateScrollWrapSize:function(){var s=this._getScrollWrapElement();
var t=this.get_childListElement();
if(!s){return;
}if(!s.style.height){s.style.height=t.offsetHeight+"px";
}if(this.get_groupSettings().get_flow()==b.ItemFlow.Vertical){s.style.width=t.offsetWidth+"px";
}},_getWidth:function(){var s=this.get_linkElement();
if(s){return s.offsetWidth;
}else{return this.get_element().offsetWidth;
}},_setWidth:function(s){var v=this.get_linkElement();
if(!v){v=this.get_element();
}if(!v){return;
}if($telerik.isOpera){this.get_element().style.cssFloat="none";
}var w=parseInt(s);
if(isNaN(w)){v.style.width=s;
if($telerik.isIE6){v.style.cssText=v.style.cssText;
}return;
}var x=w;
var u=$telerik.getPaddingBox(v).horizontal;
var t=$telerik.getBorderBox(v).horizontal;
x-=u+t;
if(x<=0){return;
}var y=v.style.width;
if(!y||x!=y){v.style.width=x+"px";
}},_clearWidth:function(){this._setWidth("auto");
},_getData:function(){var s=b.RadMenuItem.callBaseMethod(this,"_getData");
var t=this.get_navigateUrl();
if(t&&t!="#"&&(location.href+"#"!==t)){s.navigateUrl=t;
}return s;
},_loadFromDictionary:function(t,w){var u={};
for(var x in t){if(x==="__type"||x==="Attributes"){continue;
}var v=x.charAt(0).toLowerCase()+x.substr(1);
var s=t[x];
if(s===null||s===""){continue;
}u[v]=s;
}this._properties.load(u);
if(t.Attributes){this.get_attributes()._load(t.Attributes,w);
}},_replaceCssClass:function(u,t,s){u.className=u.className.replace(t,s);
},_setChildContainerPosition:function(z,A){var s=this._getAnimationContainer();
var u=this.get_parent();
var x=null;
if(u._getScrollWrapElement){x=u._getScrollWrapElement();
}if(x){this._detachChildren();
var t=this.get_element();
A+=t.offsetTop;
z+=t.offsetLeft;
var w=u.get_childListElement();
var y=parseInt(w.style.top);
if(isNaN(y)){y=0;
}if(this.get_groupSettings().get_offsetY()==0){A+=y;
}var v=parseInt(w.style.left);
if(isNaN(v)){v=0;
}if(this.get_groupSettings().get_offsetX()==0){z+=v;
if(this._getParentFlow()==b.ItemFlow.Horizontal){z=Math.max(z,0);
}}}s.style.left=(z+this.get_groupSettings().get_offsetX())+"px";
s.style.top=(A+this.get_groupSettings().get_offsetY())+"px";
},_detachChildren:function(){if(this._childrenDetached){return;
}var t=this.get_parent();
var s;
if(this.get_level()==0&&t.get_enableRootItemScroll()){var u=document.createElement("div");
u.className="rmHorizontal rmRootGroup";
u.style.position="absolute";
u.style.height="0px";
u.style.width="0px";
u.style.visibility="hidden";
u.style.left="0px";
if(t.get_rightToLeft()){u.style.cssFloat="right";
}var v=document.createElement("div");
v.className=q;
v.style.position="relative";
t.get_element().appendChild(u);
u.appendChild(v);
if($telerik.isIE){u.style.cssText=u.style.cssText;
}s=v;
}else{s=t._getAnimationContainer();
}var w=this._getAnimationContainer();
s.appendChild(w);
this._childrenDetached=true;
w._item=this;
w._itemTypeName=Object.getTypeName(this);
},_attachChildren:function(){if(this._childrenDetached){var s=this.get_element();
s.appendChild(this._getAnimationContainer());
this._childrenDetached=false;
}},_resetAnimatedElementPosition:function(){var s=this._getAnimatedElement();
s.style.top="0px";
s.style.left="0px";
},_positionChildContainer:function(){if(!this._autoScrollActive){this._saveAnimationContainerSize();
}var v=this._positionChildContainerBasic();
var x=v.left;
var z=v.top;
var t=this.get_menu();
var A=t.get_enableAutoScroll();
var s=t.get_enableScreenBoundaryDetection();
var w=false;
if(A){if(!this._applyAutoScroll(x,z)){if(this._autoScrollActive){this._removeAutoScroll();
this._autoScrollActive=false;
this._restoreAnimationContainerSize();
v=this._positionChildContainerBasic();
x=v.left;
z=v.top;
}if(s){var u=this._adjustForScreenBoundaries(x,z);
w=true;
this._applyAutoScroll(u.adjustedLeft,u.adjustedTop);
}}if(this._autoScrollActive){this._updateScrollSize();
}}if(s&&!w){this._adjustForScreenBoundaries(x,z);
}var y=this.get_textElement();
if(y){y.className="rmText "+this._getExpandClassName();
}},_positionChildContainerBasic:function(){var z=0;
var y=0;
var t=this.get_element();
var x=t.offsetHeight;
var s=t.offsetWidth;
var A=this._getAnimationContainer();
var w=A.offsetHeight;
var v=A.offsetWidth;
var B=this.get_groupSettings().get_expandDirection();
switch(B){case b.ExpandDirection.Up:z=-w;
break;
case b.ExpandDirection.Down:z=x;
break;
case b.ExpandDirection.Left:y=-v;
break;
case b.ExpandDirection.Right:y=s;
break;
}var u=this.get_menu();
if(u.get_rightToLeft()&&this.get_level()==0){y=s-v;
if(this._getParentFlow()==b.ItemFlow.Vertical){y-=s;
}}this._setChildContainerPosition(y,z);
return{left:y,top:z};
},_applyAutoScroll:function(t,s){if(this._isAutoScrollPossible()){if(!this._scroller){this._initializeAutoScroll();
this._autoScrollActive=true;
this._setChildContainerPosition(t,s);
}return true;
}return false;
},_adjustForScreenBoundaries:function(y,u){var L=this._getAnimationContainer();
var z=L.offsetHeight;
var I=L.offsetWidth;
var t=this.get_element();
var w=t.offsetHeight;
var v=t.offsetWidth;
var G=this.get_groupSettings().get_expandDirection();
var F=G;
var M=b.RadMenu._getViewPortSize();
var J=l().scrollTop();
var H=$telerik.getLocation(L);
var x=$telerik.getLocation(t);
var C=M.width-x.x-t.offsetWidth;
var s=x.x;
var K=M.height-x.y-t.offsetHeight;
var A=x.y-J;
switch(G){case b.ExpandDirection.Up:if($telerik.elementOverflowsTop(L,H)||(H.y<J&&K>A)){F=b.ExpandDirection.Down;
u=w;
}break;
case b.ExpandDirection.Down:if($telerik.elementOverflowsBottom(M,L,H)){if(x.y>L.offsetHeight){F=b.ExpandDirection.Up;
u=-z;
}}break;
case b.ExpandDirection.Left:if(H.x<l(document).scrollLeft()){if(C>s){F=b.ExpandDirection.Right;
y=v;
}}break;
case b.ExpandDirection.Right:if($telerik.elementOverflowsRight(M,L,H)){if(s>C){F=b.ExpandDirection.Left;
y=-I;
}}break;
}switch(F){case b.ExpandDirection.Down:case b.ExpandDirection.Up:if($telerik.elementOverflowsRight(M,L)){var E=M.width-(H.x+I);
var B=this.get_menu();
if(B.get_rightToLeft()&&this.get_level()==0){y+=E;
}else{y=E;
}}break;
case b.ExpandDirection.Left:case b.ExpandDirection.Right:if($telerik.elementOverflowsBottom(M,L)){var D=Math.min(z,M.height);
u=M.height-(H.y+D)-this._defaultScrollSize;
}break;
}this._setChildContainerPosition(y,u);
this._slide.set_direction(F);
return{adjustedLeft:y,adjustedTop:u};
},_closeChildren:function(v){var s=this.get_items();
for(var t=0;
t<s.get_count();
t++){var u=s.getItem(t);
u._stopAnimation();
u.set_focused(false);
u._close(v);
}},_stopAnimation:function(){if(this._slide){this._slide._stopAnimation();
}},_preventClose:function(){var s=this.get_parent();
if(this._state==b.RadMenuItemState.AboutToClose){this._clearTimeout();
this._state=b.RadMenuItemState.Open;
s._openedItem=this;
}if(s._preventClose){s._preventClose();
}},_setTimeout:function(s,t){this._timeoutRef=setTimeout(s,t);
},_clearTimeout:function(){if(this._timeoutRef){clearTimeout(this._timeoutRef);
this._timeoutRef=null;
}},_getExpandClassName:function(){return"rmExpand"+this._getExpandClass();
},_getExpandClass:function(){var s=this._getSlideDirection();
switch(s){case b.jSlideDirection.Up:return"Top";
case b.jSlideDirection.Down:return"Down";
case b.jSlideDirection.Left:return"Left";
case b.jSlideDirection.Right:return"Right";
}},_updateLinkClass:function(){if(this.get_isSeparator()||this.get_templated()){return;
}var t=o;
var s=this.get_cssClass();
if(s){t+=" "+s;
}if(this.get_focused()){t+=" "+this.get_focusedCssClass();
}var u=this.get_menu();
if(this.get_selected()&&(!u||u.get_enableSelection())){t+=" "+this.get_selectedCssClass();
}if(this._state==b.RadMenuItemState.Open){t+=" "+this.get_expandedCssClass();
}if(this._clicked){t+=" "+this.get_clickedCssClass();
}if(!this.get_enabled()){t+=" "+this.get_disabledCssClass();
}var v=this.get_linkElement();
if(v){v.className=t;
}},_updateImageSrc:function(){var s=this.get_imageUrl();
if(this._hovered&&this.get_hoveredImageUrl()){s=this.get_hoveredImageUrl();
}if(this._state==b.RadMenuItemState.Open&&this.get_expandedImageUrl()){s=this.get_expandedImageUrl();
}if(!this.get_enabled()&&this.get_disabledImageUrl()){s=this.get_disabledImageUrl();
}if(this._clicked&&this.get_clickedImageUrl()){s=this.get_clickedImageUrl();
}if(this.get_selected()&&this.get_selectedImageUrl()){s=this.get_selectedImageUrl();
}if(s&&this.get_element()){var t=this.get_imageElement();
if(!t){t=this._createImageElement();
}s=s.replace(/&amp;/ig,"&");
if(s!=t.src){t.src=s;
}}},_createImageElement:function(){this._imageElement=document.createElement("img");
this._imageElement.className=p;
if(!this.get_enabled()){this._imageElement.disabled="disabled";
}var s=this.get_linkElement()||this.get_element();
if(s.firstChild){s.insertBefore(this._imageElement,s.firstChild);
}else{s.appendChild(this._imageElement);
}return this._imageElement;
},_click:function(w){if(!this.get_enabled()){return;
}var s=this.get_menu();
var v=s._getExtendedItemClickingEventArgs(new b.RadMenuItemClickingEventArgs(this,w));
s._raiseEvent("itemClicking",v);
if(v.get_cancel()){return;
}if(s.get_clickToOpen()&&this.get_level()==0){var t=s.get_openedItem();
if(t&&t!=this){t._close(w);
}if(s._clicked){this._close(w);
}else{this._open(w);
}s._clicked=!s._clicked;
}var u=s._getExtendedItemClickedEventArgs(new b.RadMenuItemClickedEventArgs(this,w));
s._raiseEvent("itemClicked",u);
if(this._shouldNavigate()){return;
}this.set_selected(true);
if(this._shouldPostBack()){s._postback(this._getHierarchicalIndex());
}},_shouldPostBack:function(){if(!this.get_menu()){return false;
}return this.get_postBack()&&this.get_menu()._postBackReference;
},_canFocus:function(){return(!this.get_isSeparator())&&this.get_enabled()&&this.get_visible();
},_clearSiblingsWidth:function(){var s=this.get_parent();
var w=s.get_items();
for(var u=0;
u<w.get_count();
u++){var t=w.getItem(u);
if(t!=this){var v=t.get_linkElement();
if(v){v.style.width="auto";
}}if($telerik.isSafari){s.get_childListElement().style.width="auto";
}}},_doFocus:function(w){if(!this._canFocus()){return;
}this._ensureChildControls();
var s=this.get_parent();
var u=s.get_openedItem();
if(u&&u!=this){u._close(w);
}if(s._state!=b.RadMenuItemState.Open&&s.open){s._open(w);
}s._focusedItem=this;
var t=this.get_menu();
t._focusedItem=this;
var v=this.get_linkElement();
if(!this.get_focused()&&v){v.focus();
}this.get_menu()._raiseEvent("itemFocus",new b.RadMenuItemFocusEventArgs(this,w));
},_doBlur:function(u){if(this.get_isSeparator()){return;
}if(this.get_focused()){this.get_linkElement().blur();
}this.get_parent()._focusedItem=null;
var s=this.get_menu();
var t=this;
window.setTimeout(function(){if(s._focusedItem==t){s._focusedItem=null;
}},100);
this.get_menu()._raiseEvent("itemBlur",new b.RadMenuItemBlurEventArgs(this,u));
},_createChildControls:function(){b.RadMenuItem.callBaseMethod(this,"_createChildControls");
this._initializeScroller();
},_onScrollArrowMouseDown:function(){if(!this._scroller){return;
}this._scroller.changeScrollSpeed(b.ScrollerSpeed.Fast);
},_onScrollArrowMouseUp:function(){if(!this._scroller){return;
}this._scroller.changeScrollSpeed(b.ScrollerSpeed.Slow);
},_onScrollArrowMouseOver:function(u){if(!this._scroller){return;
}var s=1;
if(u==b.ArrowPosition.Top||u==b.ArrowPosition.Left){s=-1;
}var t=this.get_openedItem();
if(t){t.close();
}this._scroller.startScroll(b.ScrollerSpeed.Slow,s);
},_onScrollArrowMouseOut:function(){if(!this._scroller){return;
}this._scroller.stopScroll();
},_onKeyDown:function(u){var t=u.keyCode?u.keyCode:u.rawEvent.keyCode;
var s=this.get_menu().get_rightToLeft();
switch(t){case Sys.UI.Key.up:if(!s){this._onKeyboardUp(u);
}else{this._onKeyboardDown(u);
}break;
case Sys.UI.Key.down:if(!s){this._onKeyboardDown(u);
}else{this._onKeyboardUp(u);
}break;
case Sys.UI.Key.left:if(!s){this._onKeyboardLeft(u);
}else{this._onKeyboardRight(u);
}break;
case Sys.UI.Key.right:if(!s){this._onKeyboardRight(u);
}else{this._onKeyboardLeft(u);
}break;
case Sys.UI.Key.esc:this._onKeyboardEsc(u);
break;
default:return true;
}u.preventDefault();
return false;
},_onKeyboardUp:function(t){var s=this._getParentFlow();
if(s==b.ItemFlow.Vertical){this.focusPreviousItem(t);
}else{this.focusLastChild(t);
}},_onKeyboardDown:function(t){var s=this._getParentFlow();
if(s==b.ItemFlow.Vertical){this.focusNextItem(t);
}else{this.focusFirstChild(t);
}},_onKeyboardLeft:function(x){var u=this._getParentFlow();
if(u==b.ItemFlow.Horizontal){this.focusPreviousItem(x);
return;
}var y=this.get_items();
var s=this.get_groupSettings();
if(y.get_count()>0&&s.get_expandDirection()==b.ExpandDirection.Left){this.focusFirstChild(x);
return;
}var v=this.get_parent();
var t=null;
if(v.get_groupSettings){t=v.get_groupSettings();
}if(t&&t.get_expandDirection()==b.ExpandDirection.Right){v._focus(x);
return;
}var w=this.get_menu().get_openedItem();
if(w){w.focusPreviousItem(x);
}},_onKeyboardRight:function(x){var u=this._getParentFlow();
if(u==b.ItemFlow.Horizontal){this.focusNextItem(x);
return;
}var y=this.get_items();
var s=this.get_groupSettings();
if(y.get_count()>0&&s.get_expandDirection()==b.ExpandDirection.Right){this.focusFirstChild(x);
return;
}var v=this.get_parent();
var t=null;
if(v.get_groupSettings){t=v.get_groupSettings();
}if(t&&t.get_expandDirection()==b.ExpandDirection.Left){v.focus();
return;
}var w=this.get_menu().get_openedItem();
if(w){w.focusNextItem(x);
}},_onKeyboardEsc:function(u){var s=this.get_parent();
var t=this.get_menu();
if(s==t){this._blur(u);
}else{s._close(u);
s._focus(u);
}},_render:function(s){var t=this.get_parent().get_items().get_count()==1;
s[s.length]="<li class='"+this._determineCssClass()+"'>";
this._renderLink(s);
if(this.get_imageUrl()){this._renderImage(s);
}s[s.length]="<span class='rmText'>";
s[s.length]=this.get_text();
s[s.length]="</span></a>";
this._renderChildItems(s);
s[s.length]="</li>";
},_renderAccessKey:function(){if(this.get_isSeparator()||this.get_templated()){return;
}var t=this.get_linkElement();
if(!t){return;
}var w=this.get_linkElement().accessKey.toLowerCase();
if(!w){return;
}var v=this.get_textElement();
var s=v.innerHTML;
var u=s.toLowerCase().indexOf(w);
if(s.toLowerCase().indexOf("<u>")!=-1){return;
}if(u==-1){return;
}v.innerHTML=s.substr(0,u)+"<u>"+s.substr(u,1)+"</u>"+s.substr(u+1,s.length);
},_getIsImageOnly:function(){if(this._isImageOnly===null){this._isImageOnly=this.get_imageElement()!=null;
}return this._isImageOnly;
},_getFlowCssClass:function(){if(this.get_groupSettings().get_flow()==b.ItemFlow.Vertical){return f;
}else{return r;
}},_isWebServiceCallNeeded:function(){if(this._itemsLoading){return false;
}return(!this._itemsLoaded&&this.get_expandMode()==b.MenuItemExpandMode.WebService);
},_createLoadingItem:function(){var t=this.get_menu().get_loadingTemplate();
if(t===""){return;
}var s=new b.RadMenuItem();
this.get_items().add(s);
s.set_text(t);
},_removeLoadingItem:function(){if(this.get_menu().get_loadingTemplate()===""){return;
}var s=this.get_items().getItem(0);
this.get_items().remove(s);
},_loadChildrenFromWebService:function(){this.get_menu()._loadChildrenFromWebService(this);
},_onChildrenLoading:function(){this._itemsLoading=true;
this._createLoadingItem();
this._doOpen(null);
},_onChildrenLoaded:function(){this._removeLoadingItem();
this._itemsLoaded=true;
this._itemsLoading=false;
if(this.get_items().get_count()>0){this._updateColumnWrapSize();
this._slide.updateSize();
if(this._hovered){this._doOpen(null);
}}},_onChildrenLoadingError:function(){this._close(null);
this._removeLoadingItem();
this._itemsLoaded=false;
this._itemsLoading=false;
},_adjustSiblingsWidth:function(t){var s=this.get_parent();
if(s){this._clearSiblingsWidth();
b.RadMenu._adjustChildrenWidth(s,t);
}},_ensureRoundedCorners:function(){if(this._roundedCornersRendered){return;
}var s=this.get_menu();
if(s&&s.get_enableRoundedCorners()&&!this._getScrollWrapElement()){this._roundedCornersRendered=true;
l(this.get_childListElement()).prepend('<li class="rmTopRight"></li><li class="rmBottomLeft"></li><li class="rmBottomRight"></li><li class="rmTopFix"></li><li class="rmBottomFix"></li>');
}},_ensureShadows:function(){if(this._shadowsRendered){return;
}var s=this.get_menu();
if(s&&s.get_enableShadows()&&!this._getScrollWrapElement()){this._shadowsRendered=true;
l(this.get_childListElement()).prepend('<li class="rmTopRight rmTopShadowRight"></li><li class="rmBottomLeft rmBottomShadowLeft"></li><li class="rmBottomRight rmBottomShadowRight"></li>');
}},_ensureCorners:function(){if($telerik.isIE6||$telerik.quirksMode){var t=this.get_menu();
if(t&&t.get_enableRoundedCorners()){var s=this.get_childListElement();
setTimeout(function(){l("> .rmTopRight:not(.rmTopShadowRight)",s).height(parseInt(s.offsetHeight,10)-5);
l("> .rmTopFix, > .rmBottomFix",s).width(parseInt(s.offsetWidth,10)-5);
l("> .rmTopRight, > .rmBottomRight, > .rmBottomLeft, > .rmTopFix, > .rmBottomFix",s).each(function(){this.style.cssText=this.style.cssText;
});
});
}}}};
b.RadMenuItem.registerClass("Telerik.Web.UI.RadMenuItem",b.ControlItem);
})($telerik.$);
Type.registerNamespace("Telerik.Web.UI");
Telerik.Web.UI.RadMenuItemCollection=function(a){Telerik.Web.UI.RadMenuItemCollection.initializeBase(this,[a]);
};
Telerik.Web.UI.RadMenuItemCollection.prototype={};
Telerik.Web.UI.RadMenuItemCollection.registerClass("Telerik.Web.UI.RadMenuItemCollection",Telerik.Web.UI.ControlItemCollection);
Type.registerNamespace("Telerik.Web.UI");
(function(){var b=$telerik.$,a=Telerik.Web.UI;
b.registerEnum(a,"ItemFlow",{Vertical:0,Horizontal:1});
b.registerEnum(a,"ExpandDirection",{Auto:0,Up:1,Down:2,Left:3,Right:4});
b.registerEnum(a,"MenuRepeatDirection",{Vertical:0,Horizontal:1});
a.RadMenuItemGroupSettings=function(c,e){if(e){for(var f in e){this[f]=e[f];
}}for(var f in c){var d=this["set_"+f];
if(d){d.call(this,c[f]);
}}};
b.registerControlProperties(a.RadMenuItemGroupSettings,{flow:a.ItemFlow.Vertical,expandDirection:a.ExpandDirection.Auto,offsetX:0,offsetY:0,width:null,height:null,repeatDirection:a.MenuRepeatDirection.Vertical,repeatColumns:1});
a.RadMenuItemGroupSettings.registerClass("Telerik.Web.UI.RadMenuItemGroupSettings");
})();
(function(){var b=$telerik.$;
var a=Telerik.Web.UI;
a.MenuItemScroller=function(d,c){this._leftArrowCssClass="rmLeftArrow";
this._rightArrowCssClass="rmRightArrow";
this._topArrowCssClass="rmTopArrow";
this._bottomArrowCssClass="rmBottomArrow";
this._leftArrowDisabledCssClass="rmLeftArrowDisabled";
this._rightArrowDisabledCssClass="rmRightArrowDisabled";
this._topArrowDisabledCssClass="rmTopArrowDisabled";
this._bottomArrowDisabledCssClass="rmBottomArrowDisabled";
this._arrowsZIndex=2000;
this._scroller=null;
this._childListElement=d;
this._scrollElement=null;
this._orientation=null;
this._minScrollPosition=null;
this._itemFlow=c;
this._scrollerPositionChangedDelegate=null;
this._decArrow=null;
this._incArrow=null;
this._rtl=a.RadMenu._requiresRightToLeft(d);
};
a.MenuItemScroller.prototype={initialize:function(){this._childListElement.style.position="relative";
this._scrollElement=this._childListElement.parentNode;
this._orientation=a.ScrollerOrientation.Horizontal;
if(this._itemFlow==a.ItemFlow.Vertical){this._orientation=a.ScrollerOrientation.Vertical;
}this._scroller=new a.Scroller(this._childListElement,this._scrollElement,this._orientation);
this._scroller.initialize();
this._createArrows();
this._scroller.resetState();
this._scrollerPositionChangedDelegate=Function.createDelegate(this,this._onScrollerPositionChanged);
this._scroller.add_positionChanged(this._scrollerPositionChangedDelegate);
},dispose:function(){if(this._scroller){this._scroller.dispose();
this._scroller=null;
var c=b(this._decArrow).add(b(this._incArrow));
if($telerik.isIE){c.unbind(".menuScroller");
}c.remove();
}this._scrollerPositionChangedDelegate=null;
},updateState:function(){this._updateScrollingLimits();
this._updateArrows();
},resetState:function(){this._scroller.resetState();
},startScroll:function(d,c){this._scroller.startScroll(d,c);
},changeScrollSpeed:function(c){this._scroller.changeScrollSpeed(c);
},stopScroll:function(){this._scroller.stopScroll();
},scrollToMaxPosition:function(){this._scroller.scrollToMaxPosition();
},get_currentPosition:function(){return this._scroller._currentPosition;
},set_currentPosition:function(c){this._scroller._scrollTo(Math.max(Math.min(this._scroller._maxPosition,c),this._scroller._minPosition));
},_createArrows:function(){this._decArrow=this._createArrowDomElement();
this._incArrow=this._createArrowDomElement();
if(this._orientation==a.ScrollerOrientation.Vertical){this._decArrow.style.left="0px";
this._decArrow.style.top="0px";
this._incArrow.style.left="0px";
this._incArrow.style.bottom="0px";
}else{this._decArrow.style.top="0px";
this._decArrow.style.left="-1px";
this._incArrow.style.top="0px";
this._incArrow.style.right="-1px";
}},_createArrowDomElement:function(){var c=document.createElement("a");
c.href="#";
c.style.zIndex=this._arrowsZIndex;
c.appendChild(document.createTextNode("&nbsp;"));
if($telerik.isIE){b(c).bind("dragstart.menuScroller",function(){return false;
});
}this._scrollElement.appendChild(c);
return c;
},_updateArrows:function(){var c=this._scroller.isAtMinPosition();
var d=this._scroller.isAtMaxPosition();
if(c){this._decArrow.disabled="disabled";
this._setElementCssClass(this._decArrow,this._getDecArrowCssClass(false));
}else{this._decArrow.disabled="";
this._setElementCssClass(this._decArrow,this._getDecArrowCssClass(true));
}if(d){this._incArrow.disabled="disabled";
this._setElementCssClass(this._incArrow,this._getIncArrowCssClass(false));
}else{this._incArrow.disabled="";
this._setElementCssClass(this._incArrow,this._getIncArrowCssClass(true));
}},_updateScrollingLimits:function(){var c=0;
var f=0;
var d=0;
if(this._orientation==a.ScrollerOrientation.Vertical){c=this._childListElement.offsetHeight-this._scrollElement.offsetHeight;
f=this._decArrow.offsetHeight;
d=this._incArrow.offsetHeight;
}else{c=this._childListElement.offsetWidth-this._scrollElement.offsetWidth;
f=this._decArrow.offsetWidth;
d=this._incArrow.offsetWidth;
}var e=0;
var g=c;
if(this._rtl&&$telerik.isIE8){e=-c;
g=0;
}this._scroller.setScrollingLimits(e,g);
},_getDecArrowCssClass:function(c){if(this._orientation==a.ScrollerOrientation.Vertical){return c?this._topArrowCssClass:this._topArrowDisabledCssClass;
}else{return c?this._leftArrowCssClass:this._leftArrowDisabledCssClass;
}},_getIncArrowCssClass:function(c){if(this._orientation==a.ScrollerOrientation.Vertical){return c?this._bottomArrowCssClass:this._bottomArrowDisabledCssClass;
}else{return c?this._rightArrowCssClass:this._rightArrowDisabledCssClass;
}},_setElementCssClass:function(d,c){var e=d.className;
if(e!=c){d.className=c;
}},_onScrollerPositionChanged:function(c,d){this._updateArrows();
}};
a.MenuItemScroller.registerClass("Telerik.Web.UI.MenuItemScroller",null,Sys.IDisposable);
})();
